"""Plan 2026-06-08-004 F006 — producer-generated journey fixtures + regen guard.

The dashboard real-shell journey test
(``dashboard/tests/integration/plan-d-architecture-journey.test.js``) boots the
REAL shell on view-state payloads generated by the REAL producer
(``architecture_view_state.build_view_state``) — never hand-baked shapes. This
module owns those fixtures:

  * :func:`generate_fixtures` builds three deterministic tiny repos and runs
    the producer over them (fixed ``generated_at`` for byte-stable output):
      - present  — architecture.json present + docs/adr claims (intent + diff)
      - absent   — SAME tree, architecture_path pointed at a missing file
      - noadrs   — architecture.json present, NO docs/adr directory
  * the contract test regenerates all three in tmp and asserts deep equality
    with the committed files under ``dashboard/tests/fixtures/`` — a drifted
    fixture FAILS instead of silently pre-baking an outdated shape.

Regenerate after intentional producer changes with:

    DONTPANIC_REGEN_FIXTURES=1 python3 -m pytest \
        scripts/dontpanic_orchestrate/tests/test_plan_d_journey_fixtures_f006.py -q
"""

from __future__ import annotations

import datetime as _dt
import json
import os
import sys
from pathlib import Path

HERE = Path(__file__).resolve()
sys.path.insert(0, str(HERE.parents[2]))

from dontpanic_orchestrate import architecture_view_state as avs  # noqa: E402

REPO_ROOT = HERE.parents[3]
FIXTURES_DIR = REPO_ROOT / "dashboard" / "tests" / "fixtures"

FIXTURE_FILES = (
    "plan-d-view-state-present.json",
    "plan-d-view-state-absent.json",
    "plan-d-view-state-noadrs.json",
)

REGEN_ENV = "DONTPANIC_REGEN_FIXTURES"
REGEN_HINT = (
    f"Fixture drifted from the real producer. Regenerate with:\n"
    f"  {REGEN_ENV}=1 python3 -m pytest "
    f"scripts/dontpanic_orchestrate/tests/test_plan_d_journey_fixtures_f006.py -q"
)

# Pinned timestamp → byte-identical output across runs (and machines).
GENERATED_AT = _dt.datetime(2026, 6, 11, tzinfo=_dt.timezone.utc)

# Minimal-but-parseable architecture.json (shape mirrors
# test_plan_d_producer_parity_f005._make_repo). Fixed timestamps throughout.
_ARCHITECTURE_DOC = {
    "schema_version": "1.0",
    "generated_at": "2026-06-11T00:00:00Z",
    "source_fingerprint": {
        "algo": "sha256",
        "files_count": 1,
        "file_hashes_root": "a" * 64,
        "file_hashes": {},
        "computed_at": "2026-06-11T00:00:00Z",
    },
    "modules": [
        {
            "path": "App/main.py",
            "name": "app.main",
            "public_symbols": [],
            "imports": [],
            "summary": "entry",
        }
    ],
    "schemas": [],
    "plans": [],
}

# ADR shaped exactly for architecture_intent.extract_adr_claims:
#   _ID_RE      → "# ADR-0001: ..." heading
#   _STATUS_RE  → "Status: accepted"
#   _DATE_RE    → "Date: ..."
#   _DECISION_RE→ "## Decision" section; backticked dotted identifiers become
#                 claim references. `app.main` resolves to the as-built module
#                 node (→ aligned); `ghost_module.cache` resolves to nothing
#                 (→ documented_unimplemented). Decision prose deliberately
#                 contains no other snake_case/dotted tokens.
_ADR_DOC = """\
# ADR-0001: Use SQLite for plan state

Status: accepted
Date: 2026-06-01

## Context

We need durable local state without a server.

## Decision

We persist plan state through `app.main` and defer the
`ghost_module.cache` layer until demand exists.
"""


def _make_repo(base: Path, *, with_adr: bool) -> Path:
    """A deterministic tiny repo: python (tier-2) + swift (tier-1 heuristic
    import → unresolved target) + Dockerfile + architecture.json (+ ADR)."""
    root = base / "repo"
    root.mkdir(parents=True)
    (root / "App").mkdir()
    (root / "App" / "main.py").write_text('"""entry"""\n')
    (root / "App" / "Main.swift").write_text("import UIKit\n")
    (root / "Dockerfile").write_text("")
    target = root / "docs" / "architecture" / "architecture.json"
    target.parent.mkdir(parents=True)
    target.write_text(json.dumps(_ARCHITECTURE_DOC, sort_keys=True, indent=2) + "\n")
    if with_adr:
        adr_dir = root / "docs" / "adr"
        adr_dir.mkdir()
        (adr_dir / "0001-use-sqlite.md").write_text(_ADR_DOC)
    return root


def _build(root: Path, *, absent: bool) -> dict:
    arch_path = (root / "does-not-exist.json") if absent else None
    inputs = avs.load_inputs(
        repo_root=root,
        project_name="plan-d-fixture",
        project_display_name="Plan D Fixture",
        architecture_path=arch_path,
    )
    if absent:
        assert inputs.architecture is None
    return avs.build_view_state(inputs, repo_root=root, generated_at=GENERATED_AT)


def generate_fixtures(tmp: Path) -> dict[str, str]:
    """Build the three journey payloads from the REAL producer. Returns
    ``{fixture_filename: rendered_json_text}`` (render_view_state shape:
    sorted keys, indent 2, trailing newline)."""
    adr_repo = _make_repo(tmp / "with-adr", with_adr=True)
    noadr_repo = _make_repo(tmp / "no-adr", with_adr=False)

    present = _build(adr_repo, absent=False)
    absent = _build(adr_repo, absent=True)
    noadrs = _build(noadr_repo, absent=False)

    # Sanity guards so a producer regression cannot quietly bake fixtures
    # that no longer exercise the journeys' acceptance surface.
    assert present["layers"]["intent"]["populated"] is True
    assert any(e["taxonomy"] == "aligned" for e in present["layers"]["diff"])
    assert any(
        e["taxonomy"] == "documented_unimplemented" for e in present["layers"]["diff"]
    )
    assert present["coverage"]["confidence_ceiling"] in ("low", "medium")
    assert "baseline" in present["coverage"]
    assert absent["freshness"]["state"] == "absent"
    assert any(
        w.get("code") == "architecture_missing"
        for w in absent.get("validation_warnings", [])
    )
    assert noadrs["layers"]["intent"]["populated"] is False
    assert noadrs["layers"]["intent"]["claims"] == []
    assert noadrs["layers"]["diff"] == []
    # Confidence-hook material for F004 assertions: a heuristic import edge
    # (unresolved) and filesystem-kind nodes must exist on every payload.
    for payload in (present, absent, noadrs):
        assert any(
            e.get("type") == "heuristic_import" and e.get("resolved") is False
            for e in payload["edges"]
        ), "fixture repo must produce an unresolved heuristic_import edge"
        assert any(
            n.get("source_kind") == "filesystem" for n in payload["nodes"]
        ), "fixture repo must produce filesystem-kind baseline nodes"
        assert any(
            n.get("evidence_basis") == "unresolved" for n in payload["nodes"]
        ), "fixture repo must produce an unresolved heuristic target node"

    return {
        "plan-d-view-state-present.json": avs.render_view_state(present),
        "plan-d-view-state-absent.json": avs.render_view_state(absent),
        "plan-d-view-state-noadrs.json": avs.render_view_state(noadrs),
    }


def test_generator_is_deterministic(tmp_path: Path):
    """Two independent generations are byte-identical (fixed generated_at,
    content-hash fingerprints, sorted traversal — no wall-clock or tmp-path
    leakage)."""
    first = generate_fixtures(tmp_path / "a")
    second = generate_fixtures(tmp_path / "b")
    assert first == second


def test_committed_fixtures_match_real_producer(tmp_path: Path):
    """Regen guard: the committed dashboard fixtures must deep-equal what the
    real producer emits today. Set DONTPANIC_REGEN_FIXTURES=1 to rewrite."""
    generated = generate_fixtures(tmp_path)
    assert set(generated) == set(FIXTURE_FILES)

    # Snapshot-style bootstrap: a MISSING fixture is written on first run
    # (there is nothing to drift from); an EXISTING fixture is guarded
    # strictly and only rewritten under DONTPANIC_REGEN_FIXTURES=1.
    regen = os.environ.get(REGEN_ENV) == "1"
    FIXTURES_DIR.mkdir(parents=True, exist_ok=True)
    for name, text in generated.items():
        committed_path = FIXTURES_DIR / name
        if regen or not committed_path.is_file():
            committed_path.write_text(text, encoding="utf-8")

    for name, text in generated.items():
        committed_path = FIXTURES_DIR / name
        assert committed_path.is_file(), f"missing fixture {committed_path}\n{REGEN_HINT}"
        committed = json.loads(committed_path.read_text(encoding="utf-8"))
        fresh = json.loads(text)
        assert committed == fresh, f"{name} drifted from the producer.\n{REGEN_HINT}"
