// F006 — operator console default view. Verified against the REAL F001 model
// fixture (dashboard/tests/fixtures/operator-triage-model.json, generated by
// operator_triage.build_triage on the real 313-item fleet). Journey H1/H4/H5:
// the default view shows ALL unique live human items, non-human collapsed, one
// status line, no raw JSON, NO cap.

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import {
  deriveConsoleView,
  renderConsoleDefaultHTML,
  NEEDS_YOU_BUCKETS,
} from '../../lib/operator-console-logic.js';

const _here = dirname(fileURLToPath(import.meta.url));
const MODEL = JSON.parse(readFileSync(join(_here, '../fixtures/operator-triage-model.json'), 'utf8'));

describe('deriveConsoleView', () => {
  it('status line shows the raw -> unique -> need-you pipeline', () => {
    const v = deriveConsoleView(MODEL);
    expect(v.statusLine.raw).toBe(313);     // raw fleet
    expect(v.statusLine.unique).toBe(182);  // after dedupe
    expect(v.statusLine.needsYou).toBe(14); // needs_auth(2) + needs_decision(12)
  });

  it('needs-you = ALL unique live needs_auth + needs_decision (+ uncertain), never capped', () => {
    const v = deriveConsoleView(MODEL);
    const buckets = new Set(v.needsYou.map((i) => i.bucket));
    [...buckets].forEach((b) => expect(NEEDS_YOU_BUCKETS).toContain(b));
    // 14 > 5 — proves there is NO hard cap
    expect(v.needsYou.length).toBe(14);
    expect(v.needsYou.length).toBeGreaterThan(5);
  });

  it('uncertain rides WITH needs-you (honesty bucket, not buried)', () => {
    const withUncertain = {
      items: [
        { id: 'a', operator_bucket: 'needs_auth', exact_command: 'x', scope: 'global' },
        { id: 'u', operator_bucket: 'uncertain', exact_command: '', scope: 'global' },
      ],
      data_quality: { input_count: 2, total: 2, counts: { needs_auth: 1, uncertain: 1 } },
    };
    const v = deriveConsoleView(withUncertain);
    expect(v.needsYou.map((i) => i.id).sort()).toEqual(['a', 'u']);
  });

  it('non-human buckets are collapsed to counts, not items', () => {
    const v = deriveConsoleView(MODEL);
    expect(v.handled.agent_runnable).toBe(100);
    expect(v.handled.quiet).toBe(68);
    // none of the 100 agent_runnable items leak into the needs-you list
    expect(v.needsYou.some((i) => i.bucket === 'agent_runnable')).toBe(false);
  });
});

describe('renderConsoleDefaultHTML', () => {
  it('renders the status line, every needs-you command, and the collapsed handled line', () => {
    const v = deriveConsoleView(MODEL);
    const html = renderConsoleDefaultHTML(v);
    expect(html).toContain('313 raw → 182 unique → 14 need you');
    // every human item's one-move command is present (no cap, all 14)
    v.needsYou.forEach((i) => {
      if (i.command) expect(html).toContain(i.command.replace(/&/g, '&amp;'));
    });
    expect(html).toContain('100 an agent can run');
    expect(html).toContain('handled, not shown');
  });

  it('contains NO raw JSON', () => {
    const html = renderConsoleDefaultHTML(deriveConsoleView(MODEL));
    expect(html).not.toContain('"operator_bucket"');
    expect(html).not.toContain('[{');
    expect(html).not.toContain('}]');
  });

  it('healthy state shows the calm empty line', () => {
    const v = deriveConsoleView({ items: [], data_quality: { input_count: 0, total: 0, counts: {} } });
    const html = renderConsoleDefaultHTML(v);
    expect(v.healthy).toBe(true);
    expect(html).toContain('Nothing needs you');
  });
});
